Enable CORS for marketplacecatalog
aws/aws-sdk-js pull request #4229
Opened 2022-10-11 17:14 UTC by kiranvuyyuru

##### Checklist
- [x] non-code related change (markdown/git settings etc)

2022-10-11 17:19 UTC, trivikr requested changes
Please add `"cors": true` in https://github.com/aws/aws-sdk-js/blob/bb172cb66fc37ef7c19a7165f838b08495f46a1d/apis/metadata.json#L791-L794, and a release note.

You can refer PR https://github.com/aws/aws-sdk-js/pull/3779

2022-10-11 18:47 UTC, kiranvuyyuru commented
Added the `"cors": true` in the `metadata.json` file.

2022-10-11 19:21 UTC, trivikr requested changes
Please add a changelog by running `npm run add-change` as requested by pull request template.

You can refer example changelog in https://github.com/aws/aws-sdk-js/pull/3779

2022-10-12 02:43 UTC, trivikr approved these changes

2022-10-12 02:43 UTC, merged